### ISSUE TITLE
Binary files in repository

### ISSUE THREAD

**Issue by Dje-Bos** [DUTPD-23/InternetProviderCRM#3]
Remove binary files from repository such as .vs/IAC_project PD-23/v14, bin folder, debug, exe because they will be cause of merge conflicts. Also remove files with extension .suo.  [https://stackoverflow.com/questions/72298/should-i-add-the-visual-studio-suo-and-user-files-to-source-control?noredirect=1&lq=1](url)
![capture](https://user-images.githubusercontent.com/22388191/37367248-853b10e0-270b-11e8-86de-ccf37f5e62a9.PNG)

**Comment by PD-23** [comment]
Issue fixed in commit https://github.com/DUTPD-23/InternetProviderCRM/commit/92724092925db76b4244f527e02d9abad54bb3f4
